version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: noteapp-postgres
    environment:
      POSTGRES_DB: my_data
      POSTGRES_USER: my_data
      POSTGRES_PASSWORD: my_data
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
